### ISSUE TITLE
No Palm OS version available

### ISSUE THREAD

**Issue by lxgr** [julianbarg/juto#1]
I'd love to use this on my Palm PDA, but it doesn't seem to be compatible.

Any plans for Palm OS support?

**Comment by julianbarg** [comment]
Please check the project documents before posting any issues!

**Comment by lxgr** [comment]
The documentation doesn't open on my Palm VII either. It looks like your README.md is not XHTML 1.0 compliant and/or larger than 37 bytes. Please fix this.

**Comment by julianbarg** [comment]
Fixed this for now by removing the readme.

**Comment by lxgr** [comment]
Thank you, renders perfectly now!
