### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by lxgr** [julianbarg/juto#2]
Would be great to have a README.md, even if it's not readable on all devices.

**Comment by julianbarg** [comment]
We believe that documentation is for the WEAK and if you cannot read and interpret our code then you are not WORTHY!

**Comment by lxgr** [comment]
Makes sense, I read the code and it answers all my questions. Please close the issue to avoid confusion.

**Comment by julianbarg** [comment]
Closed for incompetence.

**Comment by lxgr** [comment]
Thank you, the issue can remain closed.
