### ISSUE TITLE
Unresponsive maintainer

### ISSUE THREAD

**Issue by lxgr** [julianbarg/juto#6]
I've proposed two pull requests in the last 5 minutes (#5, #4) and not received any reply so far.

What's up with that? Is this project abandoned? Can we have a community leadership vote ASAP please?

**Comment by julianbarg** [comment]
jules_tools is obviously experiencing a spam attack. but no worries, we will prevail! by closing superfluous issues like this one.

**Comment by lxgr** [comment]
Thank you, this can be closed.
